### Benutzer erstellen
POST http://localhost:8080/api/users/create
Content-Type: application/json

{
  "username": "dominikTest",
  "email": "dominik@example.com",
  "password": "sicheresPasswort123",
  "role": "ADMIN"
}

### Benutzer registrieren
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "neuerUser",
  "email": "neuer@example.com",
  "password": "meinPasswort123"
}

### Login testen
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "neuerUser",
  "password": "meinPasswort123"
}

### Logout testen
GET http://localhost:8080/api/users/logout
Accept: application/json

### Firma anlegen
POST http://localhost:8080/api/companies
Content-Type: application/json

{
  "name": "CodeCraft GmbH",
  "strasse": "Techstraße 42",
  "plz": "30519",
  "ort": "Hannover",
  "email": "info@codecraft.de",
  "ustIdNr": "DE123456789",
  "telefon": "+49 511 123456",
  "umsatzsteuer": true,
  "user": {
    "id": 1
  }
}